name: Sincronização de Stock Suprides-Shopify

on:
  schedule:
    # Executa a cada 2 horas
    - cron: '0 */2 * * *'
  workflow_dispatch:
    # Permite execução manual pelo GitHub

jobs:
  sync-stock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Executar script de sincronização
        env:
          SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
          SHOPIFY_STORE_NAME: ${{ secrets.SHOPIFY_STORE_NAME }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          SUPRIDES_BEARER_TOKEN: ${{ secrets.SUPRIDES_BEARER_TOKEN }}
        - name: Ver variáveis de ambiente
  run: python print_env.py

