name: sync-stock

on:
  schedule:
    - cron: '0 */2 * * *'  # Executa de 2 em 2 horas
  workflow_dispatch:       # Permite execução manual
  push:
    branches:
      - master              # Apenas corre quando fizeres push para o branch master

jobs:
  run-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar script de sincronização
        run: python sync_stock.py
